# Generated by Django 4.0.6 on 2022-08-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduEra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentform',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='studentform',
            old_name='firstName',
            new_name='FirstName',
        ),
        migrations.RenameField(
            model_name='studentform',
            old_name='lastName',
            new_name='LastName',
        ),
        migrations.RenameField(
            model_name='studentform',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='studentform',
            old_name='phoneNo',
            new_name='PhoneNo',
        ),
    ]
