# Generated by Django 4.0.6 on 2022-08-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduEra', '0002_rename_email_studentform_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('secondName', models.CharField(max_length=50)),
                ('phoneNo', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('pword', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='studentForm',
        ),
    ]
