# Generated by Django 4.0.6 on 2022-08-31 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduEra', '0003_teacherform_delete_studentform'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phoneNo', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=50)),
                ('pword', models.CharField(max_length=50)),
            ],
        ),
    ]
