# Generated by Django 4.0.6 on 2022-08-31 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduEra', '0004_studentform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentform',
            old_name='pword',
            new_name='password',
        ),
    ]
