# Generated by Django 4.0.6 on 2022-08-31 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduEra', '0005_rename_pword_studentform_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherform',
            old_name='pword',
            new_name='password',
        ),
    ]
